services:
  db:
    image: mysql:8.0
    container_name: refugio_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: refugio_mascotas
      MYSQL_USER: refugio_user
      MYSQL_PASSWORD: refugio_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - refugio_network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: .
    container_name: refugio_backend
    environment:
      - DB_HOST=db
      - DB_NAME=refugio_mascotas
      - DB_USER=refugio_user
      - DB_PASSWORD=refugio_pass
      - DB_PORT=3306
      - SECRET_KEY=desarrollo_secret_key_muy_largo_y_seguro
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - refugio_network
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: refugio_frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - refugio_network

volumes:
  mysql_data:

networks:
  refugio_network:
    driver: bridge
