name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          
      - name: Test application
        run: |
          cd backend
          python -c "import main; print('✅ Backend imports correctly')"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        run: |
          docker build -t refugio-mascotas:latest .
          
      - name: Test Docker container
        run: |
          docker-compose up -d
          sleep 30
          curl -f http://localhost:8001/health || exit 1
          docker-compose down

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy notification
        run: |
          echo "🚀 Ready for Digital Ocean deployment"
